// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: dtodba.proto

package dtodba

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *UserCreateReq) Reset() {
	*x = UserCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtodba_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateReq) ProtoMessage() {}

func (x *UserCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_dtodba_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateReq.ProtoReflect.Descriptor instead.
func (*UserCreateReq) Descriptor() ([]byte, []int) {
	return file_dtodba_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreateReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCreateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserCreateRes) Reset() {
	*x = UserCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtodba_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRes) ProtoMessage() {}

func (x *UserCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_dtodba_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRes.ProtoReflect.Descriptor instead.
func (*UserCreateRes) Descriptor() ([]byte, []int) {
	return file_dtodba_proto_rawDescGZIP(), []int{1}
}

type UserReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *UserReadReq) Reset() {
	*x = UserReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtodba_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReadReq) ProtoMessage() {}

func (x *UserReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_dtodba_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReadReq.ProtoReflect.Descriptor instead.
func (*UserReadReq) Descriptor() ([]byte, []int) {
	return file_dtodba_proto_rawDescGZIP(), []int{2}
}

func (x *UserReadReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type UserReadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	LastToken string `protobuf:"bytes,5,opt,name=Last_token,json=LastToken,proto3" json:"Last_token,omitempty"`
}

func (x *UserReadRes) Reset() {
	*x = UserReadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtodba_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReadRes) ProtoMessage() {}

func (x *UserReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_dtodba_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReadRes.ProtoReflect.Descriptor instead.
func (*UserReadRes) Descriptor() ([]byte, []int) {
	return file_dtodba_proto_rawDescGZIP(), []int{3}
}

func (x *UserReadRes) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserReadRes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserReadRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReadRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReadRes) GetLastToken() string {
	if x != nil {
		return x.LastToken
	}
	return ""
}

type UserLoginNotic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	LastToken string `protobuf:"bytes,2,opt,name=Last_token,json=LastToken,proto3" json:"Last_token,omitempty"`
}

func (x *UserLoginNotic) Reset() {
	*x = UserLoginNotic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtodba_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginNotic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginNotic) ProtoMessage() {}

func (x *UserLoginNotic) ProtoReflect() protoreflect.Message {
	mi := &file_dtodba_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginNotic.ProtoReflect.Descriptor instead.
func (*UserLoginNotic) Descriptor() ([]byte, []int) {
	return file_dtodba_proto_rawDescGZIP(), []int{4}
}

func (x *UserLoginNotic) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserLoginNotic) GetLastToken() string {
	if x != nil {
		return x.LastToken
	}
	return ""
}

var File_dtodba_proto protoreflect.FileDescriptor

var file_dtodba_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x74, 0x6f, 0x64, 0x62, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x74, 0x6f, 0x64, 0x62, 0x61, 0x22, 0x6f, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x8c, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x49, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x4c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x64, 0x62, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dtodba_proto_rawDescOnce sync.Once
	file_dtodba_proto_rawDescData = file_dtodba_proto_rawDesc
)

func file_dtodba_proto_rawDescGZIP() []byte {
	file_dtodba_proto_rawDescOnce.Do(func() {
		file_dtodba_proto_rawDescData = protoimpl.X.CompressGZIP(file_dtodba_proto_rawDescData)
	})
	return file_dtodba_proto_rawDescData
}

var file_dtodba_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dtodba_proto_goTypes = []interface{}{
	(*UserCreateReq)(nil),  // 0: dtodba.UserCreateReq
	(*UserCreateRes)(nil),  // 1: dtodba.UserCreateRes
	(*UserReadReq)(nil),    // 2: dtodba.UserReadReq
	(*UserReadRes)(nil),    // 3: dtodba.UserReadRes
	(*UserLoginNotic)(nil), // 4: dtodba.UserLoginNotic
}
var file_dtodba_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtodba_proto_init() }
func file_dtodba_proto_init() {
	if File_dtodba_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dtodba_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dtodba_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dtodba_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dtodba_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dtodba_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginNotic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dtodba_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtodba_proto_goTypes,
		DependencyIndexes: file_dtodba_proto_depIdxs,
		MessageInfos:      file_dtodba_proto_msgTypes,
	}.Build()
	File_dtodba_proto = out.File
	file_dtodba_proto_rawDesc = nil
	file_dtodba_proto_goTypes = nil
	file_dtodba_proto_depIdxs = nil
}
