// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: dtomsg.proto

package dtomsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Msg 各服務通訊格式
type Dto_Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`       // 訊號類型 "req":請求類型,需要回應結果, "notice":通知類型,不論結果都不回應
	Request string `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"` // 請求任務
	Data    []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Dto_Msg) Reset() {
	*x = Dto_Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtomsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dto_Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dto_Msg) ProtoMessage() {}

func (x *Dto_Msg) ProtoReflect() protoreflect.Message {
	mi := &file_dtomsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dto_Msg.ProtoReflect.Descriptor instead.
func (*Dto_Msg) Descriptor() ([]byte, []int) {
	return file_dtomsg_proto_rawDescGZIP(), []int{0}
}

func (x *Dto_Msg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dto_Msg) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Dto_Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request 類型回應格式
type Dto_Msg_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State   int32  `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`    // 狀態
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` // 提示訊息
	Request string `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"` // 對應請求任務
	Data    []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Dto_Msg_Res) Reset() {
	*x = Dto_Msg_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtomsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dto_Msg_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dto_Msg_Res) ProtoMessage() {}

func (x *Dto_Msg_Res) ProtoReflect() protoreflect.Message {
	mi := &file_dtomsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dto_Msg_Res.ProtoReflect.Descriptor instead.
func (*Dto_Msg_Res) Descriptor() ([]byte, []int) {
	return file_dtomsg_proto_rawDescGZIP(), []int{1}
}

func (x *Dto_Msg_Res) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Dto_Msg_Res) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Dto_Msg_Res) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Dto_Msg_Res) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dtomsg_proto protoreflect.FileDescriptor

var file_dtomsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x22, 0x4b, 0x0a, 0x07, 0x44, 0x74, 0x6f, 0x5f, 0x4d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x0b, 0x44, 0x74, 0x6f, 0x5f, 0x4d, 0x73, 0x67, 0x5f, 0x52,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dtomsg_proto_rawDescOnce sync.Once
	file_dtomsg_proto_rawDescData = file_dtomsg_proto_rawDesc
)

func file_dtomsg_proto_rawDescGZIP() []byte {
	file_dtomsg_proto_rawDescOnce.Do(func() {
		file_dtomsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_dtomsg_proto_rawDescData)
	})
	return file_dtomsg_proto_rawDescData
}

var file_dtomsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dtomsg_proto_goTypes = []interface{}{
	(*Dto_Msg)(nil),     // 0: dtomsg.Dto_Msg
	(*Dto_Msg_Res)(nil), // 1: dtomsg.Dto_Msg_Res
}
var file_dtomsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtomsg_proto_init() }
func file_dtomsg_proto_init() {
	if File_dtomsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dtomsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dto_Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dtomsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dto_Msg_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dtomsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtomsg_proto_goTypes,
		DependencyIndexes: file_dtomsg_proto_depIdxs,
		MessageInfos:      file_dtomsg_proto_msgTypes,
	}.Build()
	File_dtomsg_proto = out.File
	file_dtomsg_proto_rawDesc = nil
	file_dtomsg_proto_goTypes = nil
	file_dtomsg_proto_depIdxs = nil
}
